### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by adamjstewart** [popperized/spack#8]
It's unclear how to use this action within GitHub Actions. We should add some example usage and better documentation. Specifically, my project has hundreds of dependencies including PyTorch, so it should take several hours to compile from source. Is there a way to use pre-compiled binaries, or is this action useless until Spack has its own public binary mirror?

**Comment by acgetchell** [comment]
Here's an example of nice documentation:

https://github.com/marketplace/actions/install-clang
